// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Granola.OpenApiClient.Models;
using Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\webhook-endpoints
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebhookEndpointsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Granola.OpenApiClient.v1.webhookEndpoints.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints.Item.WithWebhookEndpointItemRequestBuilder"/></returns>
        public global::Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints.Item.WithWebhookEndpointItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("webhookEndpointId", position);
                return new global::Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints.Item.WithWebhookEndpointItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints.WebhookEndpointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhookEndpointsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/webhook-endpoints", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints.WebhookEndpointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhookEndpointsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/webhook-endpoints", rawUrl)
        {
        }
        /// <summary>
        /// List webhook endpoints
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.ListWebhookEndpointsOutput"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Granola.OpenApiClient.Models.ListWebhookEndpointsOutput?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Granola.OpenApiClient.Models.ListWebhookEndpointsOutput> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Granola.OpenApiClient.Models.ListWebhookEndpointsOutput>(requestInfo, global::Soenneker.Granola.OpenApiClient.Models.ListWebhookEndpointsOutput.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Registers an HTTPS URL to receive event deliveries. With a Workspace API key the endpoint is workspace-managed: pass `scopes: [&quot;workspace&quot;]` (the key&apos;s own scope), and `folder_ids` may only reference folders the key can list.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointOutput"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointOutput?> PostAsync(global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointOutput> PostAsync(global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointOutput>(requestInfo, global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointOutput.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List webhook endpoints
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Registers an HTTPS URL to receive event deliveries. With a Workspace API key the endpoint is workspace-managed: pass `scopes: [&quot;workspace&quot;]` (the key&apos;s own scope), and `folder_ids` may only reference folders the key can list.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints.WebhookEndpointsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints.WebhookEndpointsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints.WebhookEndpointsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
