// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    /// <summary>The object type of the audit event</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AuditEventObject
    {
        [EnumMember(Value = "audit_event")]
        #pragma warning disable CS1591
        AuditEvent,
        #pragma warning restore CS1591
    }
}
