// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateWebhookEndpointOutput : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creation time of the webhook endpoint</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The user who created this endpoint. Null for a workspace-managed endpoint (`scopes` is `[&quot;workspace&quot;]`), or when the creator&apos;s account was deleted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointCreatedBy? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointCreatedBy CreatedBy { get; set; }
#endif
        /// <summary>Whether deliveries are active</summary>
        public bool? Enabled { get; set; }
        /// <summary>The event names this endpoint is subscribed to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointEventsItem?>? Events { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointEventsItem?> Events { get; set; }
#endif
        /// <summary>Folder IDs this endpoint&apos;s delivery is restricted to, or an empty array when unrestricted. Events fire only for notes in these folders or their subfolders.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FolderIds { get; set; }
#nullable restore
#else
        public List<string> FolderIds { get; set; }
#endif
        /// <summary>The ID of the webhook endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The object property</summary>
        public global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointObject? Object { get; set; }
        /// <summary>Which notes this endpoint receives events for. `personal` covers notes the creating user owns, notes shared directly with them, and notes in private folders shared with them. `public` covers notes visible to everyone in the workspace. `workspace` is reported for endpoints created with a workspace API key: public workspace notes plus notes in spaces with Granola API access enabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointScopesItem?>? Scopes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointScopesItem?> Scopes { get; set; }
#endif
        /// <summary>Secret for verifying delivery signatures (Standard Webhooks HMAC-SHA256). Shown only once, in this response — store it securely.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SigningSecret { get; set; }
#nullable restore
#else
        public string SigningSecret { get; set; }
#endif
        /// <summary>The HTTPS URL deliveries are sent to. When `url_redacted` is true, reduced to the URL&apos;s origin.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>True when this response reduces `url` to its origin because the caller is not the endpoint&apos;s creator (the path can carry credentials). Orphaned endpoints whose creator account was deleted are returned unredacted so they can be cleaned up.</summary>
        public bool? UrlRedacted { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointOutput"/> and sets the default values.
        /// </summary>
        public CreateWebhookEndpointOutput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Granola.OpenApiClient.Models.CreateWebhookEndpointOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointCreatedBy>(global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointCreatedBy.CreateFromDiscriminatorValue); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "events", n => { Events = n.GetCollectionOfEnumValues<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointEventsItem>()?.AsList(); } },
                { "folder_ids", n => { FolderIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointObject>(); } },
                { "scopes", n => { Scopes = n.GetCollectionOfEnumValues<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointScopesItem>()?.AsList(); } },
                { "signing_secret", n => { SigningSecret = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "url_redacted", n => { UrlRedacted = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointCreatedBy>("created_by", CreatedBy);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointEventsItem>("events", Events);
            writer.WriteCollectionOfPrimitiveValues<string>("folder_ids", FolderIds);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointObject>("object", Object);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Granola.OpenApiClient.Models.WebhookEndpointScopesItem>("scopes", Scopes);
            writer.WriteStringValue("signing_secret", SigningSecret);
            writer.WriteStringValue("url", Url);
            writer.WriteBoolValue("url_redacted", UrlRedacted);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
