// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetV1Audit200ResponseEventsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action that was recorded. See the [audit events reference](/audit-events) for every action and the `data` it carries. Actions are added over time, so treat this as an open set of strings rather than a fixed list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Action { get; set; }
#nullable restore
#else
        public string Action { get; set; }
#endif
        /// <summary>Who performed the action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemActor? Actor { get; set; }
#nullable restore
#else
        public global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemActor Actor { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When Granola recorded the event. Usually the same moment as `occurred_at`, but later for events we learn about after the fact — a meeting recording is recorded once its summary finishes, and a note viewed offline is recorded when that device next reaches us. Events are returned in `collected_at` order, so this is the field that never moves under a cursor, and it carries microseconds to keep events that share a millisecond ordered.</summary>
        public DateTimeOffset? CollectedAt { get; set; }
        /// <summary>How the request that produced this event reached Granola</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemContext? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemContext Context { get; set; }
#endif
        /// <summary>Details of the action. The fields depend on the action, and their names are the ones Granola records internally, so they are camelCase rather than snake_case. See the [audit events reference](/audit-events) for the fields each action carries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemData? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemData Data { get; set; }
#endif
        /// <summary>The ID of the audit event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The object type of the audit event</summary>
        public global::Soenneker.Granola.OpenApiClient.Models.AuditEventObject? Object { get; set; }
        /// <summary>When the action happened, to the millisecond</summary>
        public DateTimeOffset? OccurredAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItem"/> and sets the default values.
        /// </summary>
        public GetV1Audit200ResponseEventsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetStringValue(); } },
                { "actor", n => { Actor = n.GetObjectValue<global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemActor>(global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemActor.CreateFromDiscriminatorValue); } },
                { "collected_at", n => { CollectedAt = n.GetDateTimeOffsetValue(); } },
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemContext>(global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemContext.CreateFromDiscriminatorValue); } },
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemData>(global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemData.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Granola.OpenApiClient.Models.AuditEventObject>(); } },
                { "occurred_at", n => { OccurredAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action", Action);
            writer.WriteObjectValue<global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemActor>("actor", Actor);
            writer.WriteDateTimeOffsetValue("collected_at", CollectedAt);
            writer.WriteObjectValue<global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemContext>("context", Context);
            writer.WriteObjectValue<global::Soenneker.Granola.OpenApiClient.Models.GetV1Audit200ResponseEventsItemData>("data", Data);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Granola.OpenApiClient.Models.AuditEventObject>("object", Object);
            writer.WriteDateTimeOffsetValue("occurred_at", OccurredAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
