// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    /// <summary>The object type of the actor</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetV1Audit200ResponseEventsItemActorObject
    {
        [EnumMember(Value = "api_key")]
        #pragma warning disable CS1591
        ApiKey,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "system")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
        [EnumMember(Value = "anonymous")]
        #pragma warning disable CS1591
        Anonymous,
        #pragma warning restore CS1591
    }
}
