// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    /// <summary>The type of object</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LegalHoldObject
    {
        [EnumMember(Value = "legal_hold")]
        #pragma warning disable CS1591
        LegalHold,
        #pragma warning restore CS1591
    }
}
