// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LegalHoldCustodian : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>When this person was named by the hold</summary>
        public DateTimeOffset? AddedAt { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier for the custodian entry</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The type of object</summary>
        public global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodianObject? Object { get; set; }
        /// <summary>When this person was removed from the hold, or null while they are named. Removed custodians are always returned, so the record of who was held survives.</summary>
        public DateTimeOffset? RemovedAt { get; set; }
        /// <summary>The person this custodian entry names. `email` is null once their Granola account has been deleted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodianUser? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodianUser User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodian"/> and sets the default values.
        /// </summary>
        public LegalHoldCustodian()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodian"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodian CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodian();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "added_at", n => { AddedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodianObject>(); } },
                { "removed_at", n => { RemovedAt = n.GetDateTimeOffsetValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodianUser>(global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodianUser.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("added_at", AddedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodianObject>("object", Object);
            writer.WriteDateTimeOffsetValue("removed_at", RemovedAt);
            writer.WriteObjectValue<global::Soenneker.Granola.OpenApiClient.Models.LegalHoldCustodianUser>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
