// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Note : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attendees of the meeting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Granola.OpenApiClient.Models.User>? Attendees { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Granola.OpenApiClient.Models.User> Attendees { get; set; }
#endif
        /// <summary>The calendar_event property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Granola.OpenApiClient.Models.NoteCalendarEvent? CalendarEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.Granola.OpenApiClient.Models.NoteCalendarEvent CalendarEvent { get; set; }
#endif
        /// <summary>The creation time of the note</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The folder membership of the note</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Granola.OpenApiClient.Models.Folder>? FolderMembership { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Granola.OpenApiClient.Models.Folder> FolderMembership { get; set; }
#endif
        /// <summary>The ID of the note</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The object type of the note</summary>
        public global::Soenneker.Granola.OpenApiClient.Models.NoteObject? Object { get; set; }
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Granola.OpenApiClient.Models.User? Owner { get; set; }
#nullable restore
#else
        public global::Soenneker.Granola.OpenApiClient.Models.User Owner { get; set; }
#endif
        /// <summary>The summary of the note in markdown format. Can be null if the note has no summary.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SummaryMarkdown { get; set; }
#nullable restore
#else
        public string SummaryMarkdown { get; set; }
#endif
        /// <summary>The summary text of the note</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SummaryText { get; set; }
#nullable restore
#else
        public string SummaryText { get; set; }
#endif
        /// <summary>The title of the note</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The inline transcript of the note. If it is too large to return inline, Get Note returns `TRANSCRIPT_TOO_LARGE`; retrieve it in pages from `/v1/notes/{note_id}/transcript`. The example below shows a macOS transcript. On iOS, Granola currently returns `speaker.source` as `microphone`, and `diarization_label` can carry anonymous `Speaker A/B/...` buckets when diarization is available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Granola.OpenApiClient.Models.Transcript>? Transcript { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Granola.OpenApiClient.Models.Transcript> Transcript { get; set; }
#endif
        /// <summary>The last update time of the note</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The URL to view the note in the Granola web app</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebUrl { get; set; }
#nullable restore
#else
        public string WebUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.Models.Note"/> and sets the default values.
        /// </summary>
        public Note()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.Note"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Granola.OpenApiClient.Models.Note CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Granola.OpenApiClient.Models.Note();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attendees", n => { Attendees = n.GetCollectionOfObjectValues<global::Soenneker.Granola.OpenApiClient.Models.User>(global::Soenneker.Granola.OpenApiClient.Models.User.CreateFromDiscriminatorValue)?.AsList(); } },
                { "calendar_event", n => { CalendarEvent = n.GetObjectValue<global::Soenneker.Granola.OpenApiClient.Models.NoteCalendarEvent>(global::Soenneker.Granola.OpenApiClient.Models.NoteCalendarEvent.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "folder_membership", n => { FolderMembership = n.GetCollectionOfObjectValues<global::Soenneker.Granola.OpenApiClient.Models.Folder>(global::Soenneker.Granola.OpenApiClient.Models.Folder.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Granola.OpenApiClient.Models.NoteObject>(); } },
                { "owner", n => { Owner = n.GetObjectValue<global::Soenneker.Granola.OpenApiClient.Models.User>(global::Soenneker.Granola.OpenApiClient.Models.User.CreateFromDiscriminatorValue); } },
                { "summary_markdown", n => { SummaryMarkdown = n.GetStringValue(); } },
                { "summary_text", n => { SummaryText = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "transcript", n => { Transcript = n.GetCollectionOfObjectValues<global::Soenneker.Granola.OpenApiClient.Models.Transcript>(global::Soenneker.Granola.OpenApiClient.Models.Transcript.CreateFromDiscriminatorValue)?.AsList(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "web_url", n => { WebUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Granola.OpenApiClient.Models.User>("attendees", Attendees);
            writer.WriteObjectValue<global::Soenneker.Granola.OpenApiClient.Models.NoteCalendarEvent>("calendar_event", CalendarEvent);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Granola.OpenApiClient.Models.Folder>("folder_membership", FolderMembership);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Granola.OpenApiClient.Models.NoteObject>("object", Object);
            writer.WriteObjectValue<global::Soenneker.Granola.OpenApiClient.Models.User>("owner", Owner);
            writer.WriteStringValue("summary_markdown", SummaryMarkdown);
            writer.WriteStringValue("summary_text", SummaryText);
            writer.WriteStringValue("title", Title);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Granola.OpenApiClient.Models.Transcript>("transcript", Transcript);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("web_url", WebUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
