// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NoteCalendarEvent : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The id of the calendar event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CalendarEventId { get; set; }
#nullable restore
#else
        public string CalendarEventId { get; set; }
#endif
        /// <summary>The title of the calendar event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventTitle { get; set; }
#nullable restore
#else
        public string EventTitle { get; set; }
#endif
        /// <summary>The invitees property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Granola.OpenApiClient.Models.CalendarInvitee>? Invitees { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Granola.OpenApiClient.Models.CalendarInvitee> Invitees { get; set; }
#endif
        /// <summary>The email of the organiser</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Organiser { get; set; }
#nullable restore
#else
        public string Organiser { get; set; }
#endif
        /// <summary>The end time of the calendar event</summary>
        public DateTimeOffset? ScheduledEndTime { get; set; }
        /// <summary>The start time of the calendar event</summary>
        public DateTimeOffset? ScheduledStartTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.Models.NoteCalendarEvent"/> and sets the default values.
        /// </summary>
        public NoteCalendarEvent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.NoteCalendarEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Granola.OpenApiClient.Models.NoteCalendarEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Granola.OpenApiClient.Models.NoteCalendarEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calendar_event_id", n => { CalendarEventId = n.GetStringValue(); } },
                { "event_title", n => { EventTitle = n.GetStringValue(); } },
                { "invitees", n => { Invitees = n.GetCollectionOfObjectValues<global::Soenneker.Granola.OpenApiClient.Models.CalendarInvitee>(global::Soenneker.Granola.OpenApiClient.Models.CalendarInvitee.CreateFromDiscriminatorValue)?.AsList(); } },
                { "organiser", n => { Organiser = n.GetStringValue(); } },
                { "scheduled_end_time", n => { ScheduledEndTime = n.GetDateTimeOffsetValue(); } },
                { "scheduled_start_time", n => { ScheduledStartTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("calendar_event_id", CalendarEventId);
            writer.WriteStringValue("event_title", EventTitle);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Granola.OpenApiClient.Models.CalendarInvitee>("invitees", Invitees);
            writer.WriteStringValue("organiser", Organiser);
            writer.WriteDateTimeOffsetValue("scheduled_end_time", ScheduledEndTime);
            writer.WriteDateTimeOffsetValue("scheduled_start_time", ScheduledStartTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
