// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SpaceObject
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "space")]
        #pragma warning disable CS1591
        Space,
        #pragma warning restore CS1591
    }
}
