// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    /// <summary>The source of the speaker. For iOS transcripts, Granola currently returns `microphone` for all transcript items because iOS currently captures a single audio stream. Clients should not assume this will never expand in the future.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SpeakerSource
    {
        [EnumMember(Value = "microphone")]
        #pragma warning disable CS1591
        Microphone,
        #pragma warning restore CS1591
        [EnumMember(Value = "speaker")]
        #pragma warning disable CS1591
        Speaker,
        #pragma warning restore CS1591
    }
}
