// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    /// <summary>Who said this relative to the note: `me` is the note-taker (the note&apos;s owner), `them` is other meeting participants. Omitted when the attribution is unknown, such as iOS transcript items that only carry an anonymous `diarization_label`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SpeakerAttribution
    {
        [EnumMember(Value = "me")]
        #pragma warning disable CS1591
        Me,
        #pragma warning restore CS1591
        [EnumMember(Value = "them")]
        #pragma warning disable CS1591
        Them,
        #pragma warning restore CS1591
    }
}
