// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Speaker : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Who said this relative to the note: `me` is the note-taker (the note&apos;s owner), `them` is other meeting participants. Omitted when the attribution is unknown, such as iOS transcript items that only carry an anonymous `diarization_label`.</summary>
        public global::Soenneker.Granola.OpenApiClient.Models.SpeakerAttribution? Attribution { get; set; }
        /// <summary>The diarized anonymous speaker label assigned in the transcript, such as `Speaker A`. This is currently only present on iOS transcripts when diarization is available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DiarizationLabel { get; set; }
#nullable restore
#else
        public string DiarizationLabel { get; set; }
#endif
        /// <summary>The resolved name of the identified speaker, such as `Alice Smith`. This is only present when a speaker could be identified for the transcript item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The source of the speaker. For iOS transcripts, Granola currently returns `microphone` for all transcript items because iOS currently captures a single audio stream. Clients should not assume this will never expand in the future.</summary>
        public global::Soenneker.Granola.OpenApiClient.Models.SpeakerSource? Source { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.Models.Speaker"/> and sets the default values.
        /// </summary>
        public Speaker()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.Speaker"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Granola.OpenApiClient.Models.Speaker CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Granola.OpenApiClient.Models.Speaker();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attribution", n => { Attribution = n.GetEnumValue<global::Soenneker.Granola.OpenApiClient.Models.SpeakerAttribution>(); } },
                { "diarization_label", n => { DiarizationLabel = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.Granola.OpenApiClient.Models.SpeakerSource>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Granola.OpenApiClient.Models.SpeakerAttribution>("attribution", Attribution);
            writer.WriteStringValue("diarization_label", DiarizationLabel);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Granola.OpenApiClient.Models.SpeakerSource>("source", Source);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
