// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    /// <summary>Include the note transcript in the response. If it is too large to return inline, Get Note returns `TRANSCRIPT_TOO_LARGE`; retrieve it in pages from `/v1/notes/{note_id}/transcript`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TranscriptInclude
    {
        [EnumMember(Value = "transcript")]
        #pragma warning disable CS1591
        Transcript,
        #pragma warning restore CS1591
    }
}
