// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateWebhookEndpointBodyEventsItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "note.access_granted")]
        #pragma warning disable CS1591
        NoteAccessGranted,
        #pragma warning restore CS1591
        [EnumMember(Value = "note.edited")]
        #pragma warning disable CS1591
        NoteEdited,
        #pragma warning restore CS1591
        [EnumMember(Value = "note.generated")]
        #pragma warning disable CS1591
        NoteGenerated,
        #pragma warning restore CS1591
    }
}
