// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateWebhookEndpointBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Pause (`false`) or resume (`true`) event deliveries. A paused endpoint keeps its configuration and signing secret; events that occur while paused are not delivered later. Omit to leave unchanged.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Event names to subscribe to; replaces the current subscriptions. Omit to leave unchanged.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBodyEventsItem?>? Events { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBodyEventsItem?> Events { get; set; }
#endif
        /// <summary>Restrict delivery to notes in these folders or any of their subfolders; replaces the current folder filter. Accepts folder IDs returned by `GET /v1/folders`. Pass an empty array to remove the filter. Omit to leave unchanged.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FolderIds { get; set; }
#nullable restore
#else
        public List<string> FolderIds { get; set; }
#endif
        /// <summary>Which notes to receive events for; replaces the current scopes. `personal` covers notes you own, notes shared directly with you, and notes in private folders shared with you. `public` covers notes visible to everyone in the workspace. Pass both for both sets of notes. Workspace admins can disable scopes for non-admin members in the workspace&apos;s API settings. A workspace-managed endpoint&apos;s scope is fixed: only `[&quot;workspace&quot;]` is accepted. Omit to leave unchanged.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBodyScopesItem?>? Scopes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBodyScopesItem?> Scopes { get; set; }
#endif
        /// <summary>The publicly reachable HTTPS URL to deliver events to. Omit to leave unchanged.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBody"/> and sets the default values.
        /// </summary>
        public UpdateWebhookEndpointBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "events", n => { Events = n.GetCollectionOfEnumValues<global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBodyEventsItem>()?.AsList(); } },
                { "folder_ids", n => { FolderIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "scopes", n => { Scopes = n.GetCollectionOfEnumValues<global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBodyScopesItem>()?.AsList(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBodyEventsItem>("events", Events);
            writer.WriteCollectionOfPrimitiveValues<string>("folder_ids", FolderIds);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Granola.OpenApiClient.Models.UpdateWebhookEndpointBodyScopesItem>("scopes", Scopes);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
