// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Granola.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WebhookEndpointObject
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "webhook_endpoint")]
        #pragma warning disable CS1591
        WebhookEndpoint,
        #pragma warning restore CS1591
    }
}
