// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Granola.OpenApiClient.Models;
using Soenneker.Granola.OpenApiClient.V1.Notes.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Granola.OpenApiClient.V1.Notes
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\notes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NotesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Granola.OpenApiClient.v1.notes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.V1.Notes.Item.WithNoteItemRequestBuilder"/></returns>
        public global::Soenneker.Granola.OpenApiClient.V1.Notes.Item.WithNoteItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("noteId", position);
                return new global::Soenneker.Granola.OpenApiClient.V1.Notes.Item.WithNoteItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.V1.Notes.NotesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/notes{?created_after*,created_before*,cursor*,folder_id*,page_size*,updated_after*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.V1.Notes.NotesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/notes{?created_after*,created_before*,cursor*,folder_id*,page_size*,updated_after*}", rawUrl)
        {
        }
        /// <summary>
        /// List notes
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.ListNotesOutput"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Granola.OpenApiClient.Models.ListNotesOutput?> GetAsync(Action<RequestConfiguration<global::Soenneker.Granola.OpenApiClient.V1.Notes.NotesRequestBuilder.NotesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Granola.OpenApiClient.Models.ListNotesOutput> GetAsync(Action<RequestConfiguration<global::Soenneker.Granola.OpenApiClient.V1.Notes.NotesRequestBuilder.NotesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Granola.OpenApiClient.Models.ListNotesOutput>(requestInfo, global::Soenneker.Granola.OpenApiClient.Models.ListNotesOutput.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List notes
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Granola.OpenApiClient.V1.Notes.NotesRequestBuilder.NotesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Granola.OpenApiClient.V1.Notes.NotesRequestBuilder.NotesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.V1.Notes.NotesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Granola.OpenApiClient.V1.Notes.NotesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Granola.OpenApiClient.V1.Notes.NotesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List notes
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NotesRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("created_after")]
            public string? CreatedAfter { get; set; }
#nullable restore
#else
            [QueryParameter("created_after")]
            public string CreatedAfter { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("created_before")]
            public string? CreatedBefore { get; set; }
#nullable restore
#else
            [QueryParameter("created_before")]
            public string CreatedBefore { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("folder_id")]
            public string? FolderId { get; set; }
#nullable restore
#else
            [QueryParameter("folder_id")]
            public string FolderId { get; set; }
#endif
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("updated_after")]
            public string? UpdatedAfter { get; set; }
#nullable restore
#else
            [QueryParameter("updated_after")]
            public string UpdatedAfter { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
