// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Granola.OpenApiClient.V1.Audit;
using Soenneker.Granola.OpenApiClient.V1.Folders;
using Soenneker.Granola.OpenApiClient.V1.Notes;
using Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Granola.OpenApiClient.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The audit property</summary>
        public global::Soenneker.Granola.OpenApiClient.V1.Audit.AuditRequestBuilder Audit
        {
            get => new global::Soenneker.Granola.OpenApiClient.V1.Audit.AuditRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The folders property</summary>
        public global::Soenneker.Granola.OpenApiClient.V1.Folders.FoldersRequestBuilder Folders
        {
            get => new global::Soenneker.Granola.OpenApiClient.V1.Folders.FoldersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notes property</summary>
        public global::Soenneker.Granola.OpenApiClient.V1.Notes.NotesRequestBuilder Notes
        {
            get => new global::Soenneker.Granola.OpenApiClient.V1.Notes.NotesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhookEndpoints property</summary>
        public global::Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints.WebhookEndpointsRequestBuilder WebhookEndpoints
        {
            get => new global::Soenneker.Granola.OpenApiClient.V1.WebhookEndpoints.WebhookEndpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
