// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Granola.OpenApiClient.Models;
using Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\legal-holds\{holdId}\custodians
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustodiansRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Granola.OpenApiClient.v1.legalHolds.item.custodians.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.Item.WithCustodianItemRequestBuilder"/></returns>
        public global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.Item.WithCustodianItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("custodianId", position);
                return new global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.Item.WithCustodianItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.CustodiansRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustodiansRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/legal-holds/{holdId}/custodians{?cursor*,page_size*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.CustodiansRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustodiansRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/legal-holds/{holdId}/custodians{?cursor*,page_size*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists the users a hold names, oldest first. Removed custodians are returned alongside active ones, each carrying `removed_at`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.ListLegalHoldCustodiansOutput"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Granola.OpenApiClient.Models.ListLegalHoldCustodiansOutput?> GetAsync(Action<RequestConfiguration<global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.CustodiansRequestBuilder.CustodiansRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Granola.OpenApiClient.Models.ListLegalHoldCustodiansOutput> GetAsync(Action<RequestConfiguration<global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.CustodiansRequestBuilder.CustodiansRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Granola.OpenApiClient.Models.ListLegalHoldCustodiansOutput>(requestInfo, global::Soenneker.Granola.OpenApiClient.Models.ListLegalHoldCustodiansOutput.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Names users on a hold, by email or by Granola user id. Idempotent: the response carries the request&apos;s full resolved set, whether each entry was newly added or already present.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.Models.AddLegalHoldCustodiansOutput"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Granola.OpenApiClient.Models.AddLegalHoldCustodiansOutput?> PostAsync(global::Soenneker.Granola.OpenApiClient.Models.AddLegalHoldCustodiansBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Granola.OpenApiClient.Models.AddLegalHoldCustodiansOutput> PostAsync(global::Soenneker.Granola.OpenApiClient.Models.AddLegalHoldCustodiansBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Granola.OpenApiClient.Models.AddLegalHoldCustodiansOutput>(requestInfo, global::Soenneker.Granola.OpenApiClient.Models.AddLegalHoldCustodiansOutput.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists the users a hold names, oldest first. Removed custodians are returned alongside active ones, each carrying `removed_at`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.CustodiansRequestBuilder.CustodiansRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.CustodiansRequestBuilder.CustodiansRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Names users on a hold, by email or by Granola user id. Idempotent: the response carries the request&apos;s full resolved set, whether each entry was newly added or already present.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Granola.OpenApiClient.Models.AddLegalHoldCustodiansBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Granola.OpenApiClient.Models.AddLegalHoldCustodiansBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.CustodiansRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.CustodiansRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Granola.OpenApiClient.V1.LegalHolds.Item.Custodians.CustodiansRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists the users a hold names, oldest first. Removed custodians are returned alongside active ones, each carrying `removed_at`.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CustodiansRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
            #pragma warning restore CS1591
#endif
            #pragma warning disable CS1591
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
            #pragma warning restore CS1591
        }
    }
}
#pragma warning restore CS0618
